In [1]:
import pandas as pd
import numpy as np
import time
import pickle
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [2]:
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)
    selectk_features=fit1.transform(indep_x)
    return selectk_features
    
def split_scalar(indep_x,dep_y):
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)
#Making confusion matrix
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,accuracy,report,x_test,y_test,cm

def logistic(x_train,y_train,x_test):
    from sklearn.linear_model import LogisticRegression
    classifier=LogisticRegression(random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def svm_linear(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel="linear",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def svm_NL(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel="rbf",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def Navie(x_train,y_train,x_test):
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def knn(x_train,y_train,x_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def DecisionTree(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion="entropy",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

def RandomForest(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10, criterion="entropy",random_state=0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

In [3]:
def selectK_classification(acclog,accsvm1,accsvmn1,accknn,accnav,accdes,accrf):
    dataframe=pd.DataFrame(index=["chiSquare"],columns=["Logistic","SVM1","SVMn1",
                                                        "KNN","Navie","Decision","Random"])
    for number,idex in enumerate(dataframe.index):
        dataframe["Logistic"][idex]=acclog[number]
        dataframe["SVM1"][idex]=accsvm1[number]
        dataframe["SVMn1"][idex]=accsvmn1[number]
        dataframe["KNN"][idex]=accknn[number]
        dataframe["Navie"][idex]=accnav[number]
        dataframe["Decision"][idex]=accdes[number]
        dataframe["Random"][idex]=accrf[number]
    return dataframe

In [7]:
dataset1=pd.read_csv("preprocessed.csv",index_col=None)
df2=dataset1

In [8]:
df2

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_M
0,842302.0,17.99,10.38,122.80,1001.0,0.118400,0.22862,0.28241,0.14710,0.2419,...,17.33,184.60,1937.05,0.16220,0.62695,0.7119,0.2654,0.41915,0.11890,1
1,842517.0,20.57,17.77,132.90,1326.0,0.084740,0.07864,0.08690,0.07017,0.1812,...,23.41,158.80,1937.05,0.12380,0.18660,0.2416,0.1860,0.27500,0.08902,1
2,20728995.5,19.69,21.25,130.00,1203.0,0.109600,0.15990,0.19740,0.12790,0.2069,...,25.53,152.50,1709.00,0.14440,0.42450,0.4504,0.2430,0.36130,0.08758,1
3,20728995.5,11.42,20.38,77.58,386.1,0.133695,0.22862,0.24140,0.10520,0.2464,...,26.50,98.87,567.70,0.19010,0.62695,0.6869,0.2575,0.41915,0.12301,1
4,20728995.5,20.29,14.34,135.10,1297.0,0.100300,0.13280,0.19800,0.10430,0.1809,...,16.67,152.20,1575.00,0.13740,0.20500,0.4000,0.1625,0.23640,0.07678,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424.0,21.56,22.39,142.00,1326.3,0.111000,0.11590,0.24390,0.13890,0.1726,...,26.40,166.10,1937.05,0.14100,0.21130,0.4107,0.2216,0.20600,0.07115,1
565,926682.0,20.13,28.25,131.20,1261.0,0.097800,0.10340,0.14400,0.09791,0.1752,...,38.25,155.00,1731.00,0.11660,0.19220,0.3215,0.1628,0.25720,0.06637,1
566,926954.0,16.60,28.08,108.30,858.1,0.084550,0.10230,0.09251,0.05302,0.1590,...,34.12,126.70,1124.00,0.11390,0.30940,0.3403,0.1418,0.22180,0.07820,1
567,927241.0,20.60,29.33,140.10,1265.0,0.117800,0.22862,0.28241,0.15200,0.2397,...,39.42,184.60,1821.00,0.16500,0.62695,0.7855,0.2650,0.40870,0.12301,1
568,92751.0,7.76,24.54,47.92,181.0,0.057975,0.04362,0.00000,0.00000,0.1587,...,30.37,59.16,268.60,0.08996,0.06444,0.0000,0.0000,0.28710,0.07039,0

In [9]:
indep_x=df.drop("diagnosis_M",axis=1)
dep_y=df["diagnosis_M"]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    float64
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
 31  diagnosis_M              569 non-null    int64
dtypes: float64(31), int64(1)
memory usage: 142.4 KB

In [27]:
kbest=selectkbest(indep_x,dep_y,6)
acclog=[]
accsvm1=[]
accsvmn1=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [28]:
kbest

array([[8.42302000e+05, 1.22800000e+02, 1.00100000e+03, 8.62000000e+01,
        1.84600000e+02, 1.93705000e+03],
       [8.42517000e+05, 1.32900000e+02, 1.32600000e+03, 7.40800000e+01,
        1.58800000e+02, 1.93705000e+03],
       [2.07289955e+07, 1.30000000e+02, 1.20300000e+03, 8.62000000e+01,
        1.52500000e+02, 1.70900000e+03],
       ...,
       [9.26954000e+05, 1.08300000e+02, 8.58100000e+02, 4.85500000e+01,
        1.26700000e+02, 1.12400000e+03],
       [9.27241000e+05, 1.40100000e+02, 1.26500000e+03, 8.62000000e+01,
        1.84600000e+02, 1.82100000e+03],
       [9.27510000e+04, 4.79200000e+01, 1.81000000e+02, 1.91500000e+01,
        5.91600000e+01, 2.68600000e+02]])

In [29]:
x_train,x_test,y_train,y_test=split_scalar(kbest,dep_y)

classifier,accuracy,report,x_test,y_test,cm=logistic(x_train,y_train,x_test)
acclog.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=svm_linear(x_train,y_train,x_test)
accsvm1.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)
accsvmn1.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=knn(x_train,y_train,x_test)
accknn.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=Navie(x_train,y_train,x_test)
accnav.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=DecisionTree(x_train,y_train,x_test)
accdes.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=RandomForest(x_train,y_train,x_test)
accrf.append(accuracy)

Result=selectK_classification(acclog,accsvm1,accsvmn1,accknn,accnav,accdes,accrf)

In [14]:
Result
#2

           Logistic      SVM1     SVMn1       KNN    Navie  Decision    Random
chiSquare  0.923077  0.923077  0.895105  0.909091  0.93007  0.881119  0.902098

In [18]:
Result
#3

           Logistic      SVM1    SVMn1       KNN     Navie  Decision    Random
chiSquare  0.937063  0.944056  0.93007  0.944056  0.923077  0.888112  0.902098

In [22]:
Result
#4

           Logistic      SVM1     SVMn1       KNN     Navie  Decision   Random
chiSquare  0.916084  0.937063  0.916084  0.895105  0.909091  0.874126  0.93007

In [26]:
Result
#5

          Logistic     SVM1    SVMn1      KNN     Navie Decision    Random
chiSquare  0.93007  0.93007  0.93007  0.93007  0.923077  0.93007  0.937063

In [30]:
Result
#6

           Logistic     SVM1    SVMn1       KNN     Navie  Decision   Random
chiSquare  0.923077  0.93007  0.93007  0.937063  0.916084  0.916084  0.93007